// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_gSNlQQNPgM0vPSAxBsaAdc8TrRC0co',
    appId: '1:903212476347:web:e66bf909df612f768c069e',
    messagingSenderId: '903212476347',
    projectId: 'pro17inventory-5a95d',
    authDomain: 'pro17inventory-5a95d.firebaseapp.com',
    storageBucket: 'pro17inventory-5a95d.appspot.com',
    measurementId: 'G-BV7SYVK0T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgChrm5kJ1nDyrRE3hoGNxo3LeG8etCsw',
    appId: '1:903212476347:android:6d133a339a0673658c069e',
    messagingSenderId: '903212476347',
    projectId: 'pro17inventory-5a95d',
    storageBucket: 'pro17inventory-5a95d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASesbfFj0uAIHwQanQufn_7pj6LDn2iWM',
    appId: '1:903212476347:ios:87fe840ec7b4520d8c069e',
    messagingSenderId: '903212476347',
    projectId: 'pro17inventory-5a95d',
    storageBucket: 'pro17inventory-5a95d.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASesbfFj0uAIHwQanQufn_7pj6LDn2iWM',
    appId: '1:903212476347:ios:72d4daa6df1596508c069e',
    messagingSenderId: '903212476347',
    projectId: 'pro17inventory-5a95d',
    storageBucket: 'pro17inventory-5a95d.appspot.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}
